set_property IOSTANDARD DIFF_SSTL15 [get_ports sys_clk_p]
set_property IOSTANDARD DIFF_SSTL15 [get_ports sys_clk_n]
set_property PACKAGE_PIN T22 [get_ports uart_txd]
set_property PACKAGE_PIN T23 [get_ports uart_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports sys_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports uart_txd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports ad9748_sleep]
set_property IOSTANDARD LVCMOS33 [get_ports led]
set_property IOSTANDARD LVCMOS33 [get_ports debug_uart_rx]
set_property IOSTANDARD LVCMOS33 [get_ports debug_uart_tx]
set_property IOSTANDARD LVCMOS33 [get_ports pwm_port]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports adc_clk_p]


set_property PACKAGE_PIN AE10 [get_ports sys_clk_p]
set_property PACKAGE_PIN AB25 [get_ports sys_rst_n]
set_property PACKAGE_PIN L12 [get_ports {pwm_diff_port_p[0]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {pwm_diff_port_p[0]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {pwm_diff_port_n[0]}]
set_property PACKAGE_PIN K14 [get_ports {pwm_diff_port_p[1]}]
set_property PACKAGE_PIN L15 [get_ports {pwm_diff_port_p[2]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {pwm_diff_port_p[1]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {pwm_diff_port_n[1]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {pwm_diff_port_p[2]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {pwm_diff_port_n[2]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports dds_clk0_p]


set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports pwm_diff_port_p]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_50M]


set_property PACKAGE_PIN AG24 [get_ports adc_clk_p]
set_property PACKAGE_PIN C27 [get_ports led]
set_property PACKAGE_PIN A15 [get_ports debug_uart_tx]
set_property PACKAGE_PIN A11 [get_ports pwm_slow_port]
set_property PACKAGE_PIN D19 [get_ports pwm_port]
set_property PACKAGE_PIN R26 [get_ports debug_uart_rx]
set_property PACKAGE_PIN V22 [get_ports ad9748_sleep]
set_property PACKAGE_PIN J11 [get_ports {dac_data[0]}]
set_property PACKAGE_PIN J12 [get_ports {dac_data[1]}]
set_property PACKAGE_PIN J16 [get_ports {dac_data[2]}]
set_property PACKAGE_PIN H16 [get_ports {dac_data[3]}]
set_property PACKAGE_PIN F11 [get_ports {dac_data[4]}]
set_property PACKAGE_PIN E11 [get_ports {dac_data[5]}]
set_property PACKAGE_PIN D11 [get_ports {dac_data[6]}]
set_property PACKAGE_PIN C11 [get_ports {dac_data[7]}]
set_property PACKAGE_PIN AD23 [get_ports dds_clk0_p]
set_property PACKAGE_PIN AE23 [get_ports pwm_diff_port_p]
